version: "3.8"
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Uncomment below to mount code for live reload (dev only)
    # volumes:
    #   - .:/app
